/* v15 — reliable multi-stage assessment and cognitive laboratory */
(()=>{'use strict';
const BASE='/pterminology-site/';
const q=(s,r=document)=>r.querySelector(s);const qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const now=()=>performance.now();
const storageKey=d=>`pterminology:v15:${d.slug}`;
const readDef=()=>{const n=q('#lab-definition');if(!n)return null;try{return JSON.parse(n.textContent)}catch(e){console.error(e);return null}};
function save(d,state){try{localStorage.setItem(storageKey(d),JSON.stringify({...state,savedAt:new Date().toISOString()}))}catch{}}
function load(d){try{return JSON.parse(localStorage.getItem(storageKey(d))||'null')}catch{return null}}
function clear(d){try{localStorage.removeItem(storageKey(d))}catch{}}
const button=(txt,cls='')=>`<button type="button" class="${cls}">${txt}</button>`;
const optionMax=(d,i)=>{const item=d.questions[i];return ((item&&item.options)||d.options||[]).length-1};
function assessmentScore(d,answers){
 const entries=Object.entries(answers).filter(([,v])=>Number.isFinite(Number(v)));const raw=entries.reduce((s,[,v])=>s+Number(v),0);
 const answered=entries.length;const maxAnswered=entries.reduce((s,[i])=>s+Math.max(0,optionMax(d,Number(i))),0);
 const percent=maxAnswered?Math.round(raw/maxAnswered*100):0;return{raw,percent,answered,total:d.questions.length,complete:answered===d.questions.length};
}
function interpretAssessment(d,score){
 const raw=score.raw;
 if(d.score_type==='phq9'){if(raw<=4)return['أعراض قليلة أو غير ظاهرة','راقب الاتجاه العام والوظيفة اليومية.'];if(raw<=9)return['أعراض خفيفة','قد تفيد المتابعة وخطوات دعم منظمة.'];if(raw<=14)return['أعراض متوسطة','ناقش النتيجة مع مختص مؤهل، خصوصًا عند التعطل.'];if(raw<=19)return['أعراض متوسطة الشدة إلى شديدة','يُنصح بتقييم مهني قريب.'];return['أعراض شديدة','اطلب تقييمًا مهنيًا سريعًا وتعامل فورًا مع أي خطر على السلامة.'];}
 if(d.score_type==='gad7'){if(raw<=4)return['قلق قليل أو غير ظاهر','راقب التغير والسياق.'];if(raw<=9)return['قلق خفيف','قد تفيد مهارات التعامل والمتابعة.'];if(raw<=14)return['قلق متوسط','ناقش الأثر الوظيفي مع مختص.'];return['قلق شديد','يُنصح بتقييم مهني قريب.'];}
 if(d.score_type==='who5'){if(score.percent<28)return['عافية منخفضة جدًا','النتيجة المنخفضة تستحق مناقشة مهنية، خصوصًا مع التعطل أو اليأس.'];if(score.percent<50)return['عافية منخفضة','تابع الاتجاه وفكر في دعم منظم.'];if(score.percent<72)return['عافية متوسطة','حافظ على العوامل الداعمة وراقب التغير.'];return['عافية جيدة نسبيًا','استخدم النتيجة للمقارنة مع نفسك عبر الزمن.'];}
 if(d.score_type==='audit_guided')return['مراجعة استرشادية','هذه الصفحة لا تحسب درجة AUDIT السريرية الرسمية؛ استخدمها لتنظيم المعلومات ومناقشتها مع مختص.'];
 if(score.percent<25)return['احتياج محدود حاليًا','المؤشرات المبلغ عنها قليلة في البنود التي أجبت عنها.'];if(score.percent<50)return['احتياج خفيف إلى متوسط','توجد مجالات تستحق المتابعة وخطوات دعم محددة.'];if(score.percent<75)return['احتياج مرتفع','الأثر واضح نسبيًا ويستحق خطة دعم ومراجعة.'];return['احتياج مرتفع جدًا','الأثر المبلغ عنه شديد؛ اطلب تقييمًا مهنيًا عند التعطل أو الخطر.'];
}
function showAssessmentResult(d,state,final=false){
 const box=q('.result-card');if(!box)return;const score=assessmentScore(d,state.answers);const [title,desc]=interpretAssessment(d,score);
 const missing=score.total-score.answered;let safety='';if(d.slug==='phq-9-plus'&&Number(state.answers[8]||0)>0)safety='<p class="lab-alert"><strong>تنبيه سلامة:</strong> وجود أفكار عن الموت أو إيذاء النفس يحتاج تواصلًا فوريًا مع شخص موثوق أو خدمة طوارئ محلية أو مختص. لا تبق وحدك مع خطر وشيك.</p>';
 box.innerHTML=`<span class="lab-v12__badge">${final&&score.complete?'النتيجة النهائية':'نتيجة حالية'}</span><h2>${title}</h2><div class="result-score">${d.score_type==='who5'?score.percent+'%':score.raw}</div><p>أُجيب عن ${score.answered} من ${score.total} بندًا${missing?`، ويتبقى ${missing}`:''}.</p><p>${desc}</p>${safety}<p><small>هذه النتيجة تثقيفية أو للفحص الأولي، وليست تشخيصًا فرديًا.</small></p>`;
 box.dataset.visible='true';box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'nearest'});
}
function assessmentEngine(host,d){
 const saved=load(d);const totalStages=Math.min(5,Math.max(1,Math.ceil(d.questions.length/3)));const state=saved||{stage:0,answers:{}};const per=Math.ceil(d.questions.length/totalStages);
 function render(){const start=state.stage*per,end=Math.min(d.questions.length,start+per),items=d.questions.slice(start,end);
 host.innerHTML=`<div class="lab-engine"><div class="stage-bar"><span style="width:${((state.stage+1)/totalStages)*100}%"></span></div><div class="stage-meta"><strong>المرحلة ${state.stage+1} من ${totalStages}</strong><span>${Object.keys(state.answers).length}/${d.questions.length} إجابة</span></div><div class="lab-inline-error" role="alert" hidden></div><form class="assessment-form">${items.map((item,i)=>{const idx=start+i,opts=item.options||d.options||['لا ينطبق','قليلًا','أحيانًا','غالبًا','بدرجة شديدة'];return`<fieldset class="question"><legend>${idx+1}. ${typeof item==='string'?item:item.text}</legend><div class="answer-grid">${opts.map((o,v)=>`<label><input type="radio" name="q${idx}" value="${v}" ${String(state.answers[idx])===String(v)?'checked':''}><span>${o}</span></label>`).join('')}</div></fieldset>`}).join('')}</form><div class="game-actions">${button('السابق','secondary prev')}${button(state.stage===totalStages-1?'إنهاء وإظهار النتيجة':'المرحلة التالية','next')}${button('إظهار النتيجة الحالية','secondary interim')}${button('حفظ وتوقف','secondary pause')}${button('بدء جديد','secondary restart')}</div><section class="result-card" aria-live="polite" hidden></section></div>`;
 qa('input',host).forEach(x=>x.addEventListener('change',e=>{state.answers[Number(e.target.name.slice(1))]=Number(e.target.value);save(d,state)}));
 const prev=q('.prev',host);prev.disabled=state.stage===0;prev.onclick=()=>{state.stage--;save(d,state);render()};
 q('.next',host).onclick=()=>{qa('input:checked',host).forEach(x=>state.answers[Number(x.name.slice(1))]=Number(x.value));const missing=[];for(let i=start;i<end;i++)if(state.answers[i]===undefined)missing.push(i);if(missing.length){const err=q('.lab-inline-error',host);err.hidden=false;err.textContent=`أجب عن ${missing.length} بند في هذه المرحلة قبل المتابعة.`;q(`input[name="q${missing[0]}"]`,host)?.focus();return;}save(d,state);if(state.stage<totalStages-1){state.stage++;render();window.scrollTo({top:host.offsetTop-20,behavior:'smooth'});}else showAssessmentResult(d,state,true)};
 q('.interim',host).onclick=()=>showAssessmentResult(d,state,false);q('.pause',host).onclick=()=>{save(d,state);alert('تم حفظ تقدمك على هذا الجهاز. يمكنك العودة لاحقًا.');};q('.restart',host).onclick=()=>{if(confirm('هل تريد مسح الإجابات والبدء من جديد؟')){clear(d);state.stage=0;state.answers={};render();}};
 }
 render();
}
function seeded(seed){let x=seed|0;return()=>((x=Math.imul(1664525,x)+1013904223|0)>>>0)/4294967296}
function shuffle(arr,rnd){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}
function unique(values){return [...new Map(values.map(v=>[String(v),v])).values()]}
const COLORS=[{label:'وردي',value:'وردي',hex:'#ef6f9f'},{label:'تركواز',value:'تركواز',hex:'#21b7ad'},{label:'بنفسجي',value:'بنفسجي',hex:'#8c6bd8'},{label:'خوخي',value:'خوخي',hex:'#ed8e6f'}];
function makeTrial(d,stage,index){
 const rnd=seeded((d.slug.length+1)*999+stage*71+index*13),mode=d.mode||d.category||'',slug=d.slug||'';let prompt='',options=[],answer='',kind='text',explanation='';
 if(/السرعة/.test(mode)||/reaction|auditory-symbol/.test(slug)){const target=COLORS[Math.floor(rnd()*COLORS.length)];prompt=`اختر اللون: ${target.label}`;answer=target.value;options=shuffle(COLORS,rnd);kind='color';explanation=`الإجابة الصحيحة هي ${target.label}.`;}
 else if(/الكبح/.test(mode)||/go-no-go|stroop|inhibition/.test(slug)){const word=COLORS[Math.floor(rnd()*COLORS.length)],ink=COLORS[Math.floor(rnd()*COLORS.length)];prompt=`اختر لون الحبر لا معنى الكلمة: ${word.label}`;answer=ink.value;options=shuffle(COLORS,rnd);kind='stroop';explanation=`لون الحبر المستهدف هو ${ink.label}.`;}
 else if(/الذاكرة العاملة/.test(mode)){const nums=Array.from({length:3+stage},()=>Math.floor(rnd()*9)+1);if(/backward/.test(slug)){prompt=`ما أول رقم عند عكس التسلسل ${nums.join(' – ')}؟`;answer=String(nums[nums.length-1]);}else{prompt=`ما آخر رقم في التسلسل ${nums.join(' – ')}؟`;answer=String(nums[nums.length-1]);}options=shuffle(unique([answer,String((Number(answer)+1)%10),String((Number(answer)+2)%10),String(Math.max(0,Number(answer)-1))]),rnd);explanation=`الإجابة هي ${answer}.`;}
 else if(/الذاكرة/.test(mode)){const symbols=['●','▲','■','★','◆','☀'];const seq=Array.from({length:4+stage},()=>symbols[Math.floor(rnd()*symbols.length)]);const pos=Math.min(seq.length-1,1+Math.floor(rnd()*(seq.length-1)));prompt=`ما الرمز رقم ${pos+1} في التسلسل: ${seq.join('  ')}؟`;answer=seq[pos];options=shuffle(unique([answer,...shuffle(symbols,rnd).filter(x=>x!==answer).slice(0,3)]),rnd);explanation=`الرمز في الموضع ${pos+1} هو ${answer}.`;}
 else if(/الانتباه/.test(mode)){const target=['★','●','▲'][Math.floor(rnd()*3)];const count=2+Math.floor(rnd()*4);const distract=['○','△','◇'];const row=shuffle([...Array(count).fill(target),...Array(8-count).fill(0).map(()=>distract[Math.floor(rnd()*distract.length)])],rnd);prompt=`كم مرة يظهر ${target}؟ ${row.join(' ')}`;answer=String(count);options=shuffle(unique([answer,String(count+1),String(Math.max(0,count-1)),String(count+2)]),rnd);explanation=`ظهر الرمز ${count} مرات.`;}
 else if(/الاستدلال/.test(mode)){const a=Math.floor(rnd()*8)+2,b=Math.floor(rnd()*5)+1;prompt=`أكمل النمط: ${a}، ${a+b}، ${a+2*b}، ؟`;answer=String(a+3*b);options=shuffle(unique([answer,String(a+4*b),String(a+2*b+1),String(Math.max(0,a+3*b-2))]),rnd);explanation=`يزداد التسلسل بمقدار ${b}.`;}
 else if(/المرونة/.test(mode)){const rule=stage%2===0?'اختر الأكبر':'اختر الأصغر';const a=Math.floor(rnd()*20)+1,b=Math.floor(rnd()*20)+1;prompt=`القاعدة الحالية: ${rule}. اختر بين ${a} و${b}.`;answer=String(stage%2===0?Math.max(a,b):Math.min(a,b));options=shuffle(unique([String(a),String(b),String(a+b),String(Math.abs(a-b))]),rnd);explanation=`طُبقت قاعدة ${rule}.`;}
 else if(/المكانية/.test(mode)){const arrows=['↑','→','↓','←'];const start=Math.floor(rnd()*4),turns=1+Math.floor(rnd()*3);prompt=`إذا دار السهم ${arrows[start]} ربع دورة مع عقارب الساعة ${turns} مرة، فأين يشير؟`;answer=arrows[(start+turns)%4];options=shuffle(arrows,rnd);explanation=`بعد ${turns} دورة يصبح الاتجاه ${answer}.`;}
 else if(/التنفيذية/.test(mode)){const sets=[{p:'لديك موعد صباحي. ما الخطوة الأولى الأكثر فائدة؟',o:['تجهيز الوثائق والوقت','فتح تطبيقات كثيرة','تأجيل المنبه','البدء بمهمة أخرى'],a:'تجهيز الوثائق والوقت'},{p:'مهمة كبيرة غير واضحة. ما البداية الأفضل؟',o:['تحديد ناتج صغير وخطوة أولى','انتظار الدافع الكامل','تنفيذ كل شيء معًا','تغيير الهدف كل دقيقة'],a:'تحديد ناتج صغير وخطوة أولى'}];const s=sets[Math.floor(rnd()*sets.length)];prompt=s.p;answer=s.a;options=shuffle(s.o,rnd);explanation='الاختيار الأفضل يقلل الغموض ويحدد خطوة قابلة للتنفيذ.';}
 else if(/الاجتماعية/.test(mode)){const s={p:'قال صديق: «كان يومي صعبًا». ما الاستجابة الأكثر تعاطفًا؟',o:['يبدو أنك متعب، هل تريد أن أستمع؟','الأمر بسيط، انسَه','أنا مررت بما هو أسوأ','لماذا تتصرف هكذا؟'],a:'يبدو أنك متعب، هل تريد أن أستمع؟'};prompt=s.p;answer=s.a;options=shuffle(s.o,rnd);explanation='الاستجابة التعاطفية تعترف بالشعور وتعرض الاستماع دون تقليل.';}
 else if(/اللغة/.test(mode)){const sets=[['هادئ','مطمئن','مستقر','منفعل'],['استماع','احترام','وضوح','تهديد'],['تعاون','مشاركة','مساندة','عزلة']];const s=sets[Math.floor(rnd()*sets.length)];prompt='اختر العنصر المختلف عن المجموعة';answer=s[3];options=shuffle(s,rnd);explanation=`العنصر المختلف هو ${answer}.`;}
 else{const target=Math.floor(rnd()*9)+1;prompt=`اختر الرقم ${target}`;answer=String(target);options=shuffle([String(target),String((target+1)%10),String((target+2)%10),String((target+3)%10)],rnd);explanation=`الرقم المطلوب هو ${target}.`;}
 return{prompt,options,answer,kind,explanation};
}
function optionHtml(option,trial){const value=typeof option==='object'?option.value:String(option),label=typeof option==='object'?option.label:String(option),hex=typeof option==='object'?option.hex:'';return`<button type="button" class="choice-button ${trial.kind==='color'||trial.kind==='stroop'?'color-choice':''}" data-value="${value.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}" ${hex?`style="--choice-color:${hex}"`:''}><span>${label}</span></button>`;}
function cognitiveResult(d,state,final=false){const box=q('.result-card');if(!box)return;const trials=state.trials||[],correct=trials.filter(x=>x.correct).length,acc=trials.length?Math.round(correct/trials.length*100):0,times=trials.map(x=>x.time).filter(Boolean).sort((a,b)=>a-b),median=times.length?Math.round(times[Math.floor(times.length/2)]):0;const completedStages=new Set(trials.map(x=>x.stage)).size;const composite=trials.length?Math.round(acc*.75+clamp(1600-median,0,1600)/1600*25):0;box.innerHTML=`<span class="lab-v12__badge">${final?'النتيجة النهائية':'نتيجة حالية'}</span><h2>ملخص الأداء التدريبي</h2><div class="result-score">${composite}</div><p><strong>الدقة:</strong> ${acc}% · <strong>الزمن الوسيط:</strong> ${median||'—'} مللي ثانية · <strong>المحاولات:</strong> ${trials.length} · <strong>المراحل:</strong> ${completedStages}</p><p>${trials.length?'قارن الأداء بنفسك عبر جلسات متشابهة، وركز على الدقة قبل السرعة.':'ابدأ محاولة واحدة على الأقل لعرض نتيجة ذات معنى.'}</p><p><small>هذه ليست درجة IQ ولا معيارًا سريريًا.</small></p>`;box.dataset.visible='true';box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'nearest'});}
function cognitiveEngine(host,d){const saved=load(d),state=saved||{stage:0,trials:[],trial:0},stages=d.stages||5,per=d.trials_per_stage||6;let started=0,current=null,timer=0;
 function renderStage(){host.innerHTML=`<div class="lab-engine"><div class="stage-bar"><span style="width:${((state.stage+1)/stages)*100}%"></span></div><div class="stage-meta"><strong>المرحلة ${state.stage+1} من ${stages}</strong><span>${state.trials.length} محاولة محفوظة</span></div><div class="timer-card"><div class="stimulus" aria-live="polite">جاهز؟</div><div class="game-actions">${button('ابدأ المحاولة','start')}${button('إظهار النتيجة الحالية','secondary interim')}${button('حفظ وتوقف','secondary pause')}${button('بدء جديد','secondary restart')}</div></div><section class="result-card" aria-live="polite" hidden></section></div>`;q('.start',host).onclick=nextTrial;q('.interim',host).onclick=()=>cognitiveResult(d,state,false);q('.pause',host).onclick=()=>{save(d,state);alert('تم حفظ المرحلة والنتائج على جهازك.');};q('.restart',host).onclick=()=>{if(confirm('بدء جديد ومسح النتائج؟')){clearTimeout(timer);clear(d);state.stage=0;state.trial=0;state.trials=[];renderStage();}};}
 function nextTrial(){if(state.trial>=per){state.trial=0;if(state.stage>=stages-1){save(d,state);cognitiveResult(d,state,true);return;}state.stage++;save(d,state);renderStage();return;}current=makeTrial(d,state.stage,state.trial);started=now();const stim=q('.stimulus',host);stim.innerHTML=`<div class="trial-card"><p>${current.prompt}</p><div class="choice-grid">${current.options.map(o=>optionHtml(o,current)).join('')}</div><div class="trial-feedback" role="status"></div></div>`;qa('[data-value]',stim).forEach(b=>b.onclick=()=>{if(b.disabled)return;qa('[data-value]',stim).forEach(x=>x.disabled=true);const value=b.dataset.value,correct=String(value)===String(current.answer);b.classList.add(correct?'is-correct':'is-wrong');qa('[data-value]',stim).forEach(x=>{if(String(x.dataset.value)===String(current.answer))x.classList.add('is-correct')});state.trials.push({correct,time:Math.round(now()-started),stage:state.stage,slug:d.slug});state.trial++;save(d,state);q('.trial-feedback',stim).textContent=`${correct?'✓ صحيح':'✦ ليست الإجابة الصحيحة'}. ${current.explanation}`;timer=setTimeout(nextTrial,850);});}
 renderStage();}
function legacyFix(){if(q('[data-v12-lab]'))return;const path=location.pathname;if(!/assessments|cognitive-tests/.test(path))return;qa('[id*="result" i],[class*="result" i],[hidden]').forEach(el=>{el.hidden=false;el.classList.add('legacy-result-fix')});}
function boot(){document.documentElement.dataset.lab='v15';const d=readDef(),a=q('[data-v12-lab="assessment"]'),c=q('[data-v12-lab="cognitive"]');if(d&&a)assessmentEngine(a,d);if(d&&c)cognitiveEngine(c,d);legacyFix();if('serviceWorker'in navigator)navigator.serviceWorker.register(BASE+'sw.js?v=15').catch(()=>{});}
globalThis.__PTERMINOLOGY_LAB_V15__={makeTrial,assessmentScore,interpretAssessment};
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}
})();
