/* v12 direct multi-stage assessment engine */
(()=>{'use strict';
const BASE='/pterminology-site/';const q=(s,r=document)=>r.querySelector(s);const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const now=()=>performance.now();const storageKey=d=>`pterminology:v12:${d.slug}`;
const readDef=()=>{const n=q('#lab-definition');if(!n)return null;try{return JSON.parse(n.textContent)}catch(e){console.error(e);return null}};
function pastelize(root=document){const scope=root instanceof Element?[root,...qa('main,section,article,aside,header,footer,nav,div',root)]:qa('body,main,section,article,aside,header,footer,nav,div',root);scope.forEach(el=>{if(el.dataset.m12Checked==='1')return;el.dataset.m12Checked='1';const s=getComputedStyle(el),m=s.backgroundColor.match(/rgba?\((\d+)[, ]+(\d+)[, ]+(\d+)/);if(!m)return;const [r,g,b]=m.slice(1).map(Number),lum=.2126*r+.7152*g+.0722*b;if(lum<75&&!el.classList.contains('m12-dark-replaced'))el.classList.add('m12-dark-replaced')});document.documentElement.dataset.marshmallow='v12'}
function save(d,state){localStorage.setItem(storageKey(d),JSON.stringify({...state,savedAt:new Date().toISOString()}))}
function load(d){try{return JSON.parse(localStorage.getItem(storageKey(d))||'null')}catch{return null}}
function clear(d){localStorage.removeItem(storageKey(d))}
const button=(txt,cls='')=>`<button type="button" class="${cls}">${txt}</button>`;
function resultBand(p){if(p<25)return['منخفض حاليًا','الدرجة الحالية في النطاق المنخفض. راقب التغير والسياق بدل الاعتماد على رقم واحد.'];if(p<50)return['خفيف إلى متوسط','توجد إشارات تستحق الانتباه وخطوات دعم بسيطة ومتابعة منتظمة.'];if(p<75)return['مرتفع','الأثر واضح نسبيًا. فكر في مناقشته مع مختص مؤهل، خصوصًا عند تعطل الحياة اليومية.'];return['مرتفع جدًا','الأعراض أو الصعوبات المبلغ عنها شديدة. اطلب تقييمًا مهنيًا، وتعامل فورًا مع أي خطر على السلامة.']}
function assessmentScore(d,answers){const vals=Object.values(answers).map(Number);if(!vals.length)return{raw:0,percent:0,answered:0};let raw=vals.reduce((a,b)=>a+b,0),max=0;if(d.score_type==='who5'){max=d.questions.length*5;return{raw,percent:Math.round(raw/max*100),answered:vals.length,label:'مؤشر العافية'}}max=d.questions.reduce((a,x)=>a+((x.options||d.options||[]).length-1),0);return{raw,percent:Math.round(raw/Math.max(1,max)*100),answered:vals.length}}
function showAssessmentResult(d,state,final=false){const box=q('.result-card'),score=assessmentScore(d,state.answers),[title,desc]=resultBand(score.percent);let safety='';if(d.slug==='phq-9-plus'&&Number(state.answers[8]||0)>0)safety='<p><strong>تنبيه سلامة:</strong> وجود أفكار عن الموت أو إيذاء النفس يحتاج تواصلًا فوريًا مع شخص موثوق أو خدمة طوارئ محلية أو مختص. لا تبق وحدك مع خطر وشيك.</p>';box.innerHTML=`<span class="lab-v12__badge">${final?'النتيجة النهائية':'نتيجة مؤقتة'}</span><h2>${d.score_type==='who5'?'العافية الحالية':title}</h2><div class="result-score">${score.percent}%</div><p>أُجيب عن ${score.answered} من ${d.questions.length} بندًا. الدرجة الخام: ${score.raw}.</p><p>${d.score_type==='who5'?'الدرجة الأعلى تعكس عافية أفضل؛ استخدمها للمقارنة مع نفسك عبر الوقت.':desc}</p>${safety}<p><small>هذه النتيجة تثقيفية أو للفحص الأولي، وليست تشخيصًا فرديًا.</small></p>`;box.dataset.visible='true';box.scrollIntoView({behavior:'smooth',block:'nearest'})}
function assessmentEngine(host,d){const saved=load(d);const totalStages=4,state=saved||{stage:0,answers:{}};const per=Math.ceil(d.questions.length/totalStages);
function render(){const start=state.stage*per,end=Math.min(d.questions.length,start+per),items=d.questions.slice(start,end);host.innerHTML=`<div class="lab-engine"><div class="stage-bar"><span style="width:${((state.stage+1)/totalStages)*100}%"></span></div><div class="stage-meta"><strong>المرحلة ${state.stage+1} من ${totalStages}</strong><span>${Object.keys(state.answers).length}/${d.questions.length} إجابة</span></div><form class="assessment-form">${items.map((item,i)=>{const idx=start+i,opts=item.options||d.options||['لا ينطبق','قليلًا','أحيانًا','غالبًا','شديدًا'];return`<fieldset class="question"><legend>${idx+1}. ${typeof item==='string'?item:item.text}</legend><div class="answer-grid">${opts.map((o,v)=>`<label><input type="radio" name="q${idx}" value="${v}" ${String(state.answers[idx])===String(v)?'checked':''}><span>${o}</span></label>`).join('')}</div></fieldset>`}).join('')}</form><div class="game-actions">${button('السابق','secondary prev')}${button(state.stage===totalStages-1?'إنهاء وإظهار النتيجة':'المرحلة التالية','next')}${button('إظهار النتيجة الحالية','secondary interim')}${button('حفظ وتوقف','secondary pause')}${button('بدء جديد','secondary restart')}</div><section class="result-card" aria-live="polite"></section></div>`;
qa('input',host).forEach(x=>x.addEventListener('change',e=>{state.answers[Number(e.target.name.slice(1))]=Number(e.target.value);save(d,state)}));q('.prev',host).disabled=state.stage===0;q('.prev',host).onclick=()=>{state.stage--;save(d,state);render()};q('.next',host).onclick=()=>{qa('input:checked',host).forEach(x=>state.answers[Number(x.name.slice(1))]=Number(x.value));save(d,state);if(state.stage<totalStages-1){state.stage++;render();scrollTo({top:host.offsetTop-20,behavior:'smooth'})}else showAssessmentResult(d,state,true)};q('.interim',host).onclick=()=>showAssessmentResult(d,state,false);q('.pause',host).onclick=()=>{save(d,state);alert('تم حفظ تقدمك على هذا الجهاز. يمكنك إغلاق الصفحة والعودة لاحقًا.')};q('.restart',host).onclick=()=>{if(confirm('هل تريد مسح الإجابات والبدء من جديد؟')){clear(d);state.stage=0;state.answers={};render()}}}
render()}
function seeded(seed){let x=seed|0;return()=>((x=Math.imul(1664525,x)+1013904223|0)>>>0)/4294967296}
function makeTrial(d,stage,index){const rnd=seeded((d.slug.length+1)*999+stage*71+index*13),mode=d.mode||d.category;let prompt='',options=[],answer=0;if(/السرعة|الكبح/.test(mode)){const colors=['وردي','تركواز','بنفسجي','خوخي'];answer=Math.floor(rnd()*4);prompt=`اختر: ${colors[answer]}`;options=colors}else if(/الذاكرة/.test(mode)){const nums=Array.from({length:3+stage},()=>Math.floor(rnd()*9)+1);prompt=`ما آخر رقم في التسلسل: ${nums.join(' – ')}؟`;answer=nums[nums.length-1];options=[answer,...Array.from({length:3},()=>Math.floor(rnd()*9)+1)].sort(()=>rnd()-.5)}else if(/الاستدلال|المرونة|التنفيذية/.test(mode)){const a=Math.floor(rnd()*8)+2,b=Math.floor(rnd()*5)+1;prompt=`أكمل النمط: ${a}، ${a+b}، ${a+2*b}، ؟`;answer=a+3*b;options=[answer,answer+b,answer-b,answer+2].sort(()=>rnd()-.5)}else if(/اللغة|الاجتماعية/.test(mode)){const sets=[['هادئ','مطمئن','مستقر','منفعل'],['استماع','احترام','وضوح','تهديد'],['تعاون','مشاركة','مساندة','عزلة']];const s=sets[Math.floor(rnd()*sets.length)];prompt='اختر العنصر المختلف عن المجموعة';answer=s[3];options=[...s].sort(()=>rnd()-.5)}else{const target=Math.floor(rnd()*9)+1;prompt=`حدد الرقم ${target}`;answer=target;options=[target,(target+1)%10,(target+2)%10,(target+3)%10].sort(()=>rnd()-.5)}return{prompt,options,answer}}
function cognitiveResult(d,state,final=false){const box=q('.result-card'),trials=state.trials||[],correct=trials.filter(x=>x.correct).length,acc=trials.length?Math.round(correct/trials.length*100):0,times=trials.map(x=>x.time).filter(Boolean).sort((a,b)=>a-b),median=times.length?Math.round(times[Math.floor(times.length/2)]):0,composite=Math.round(acc*.7+clamp(1200-median,0,1200)/1200*30);box.innerHTML=`<span class="lab-v12__badge">${final?'النتيجة النهائية':'نتيجة مؤقتة'}</span><h2>ملخص الأداء التدريبي</h2><div class="result-score">${composite}</div><p><strong>الدقة:</strong> ${acc}% · <strong>الزمن الوسيط:</strong> ${median||'—'} مللي ثانية · <strong>المحاولات:</strong> ${trials.length}</p><p>قارن أداءك بنفسك عبر جلسات متشابهة. هذه ليست درجة IQ ولا معيارًا سريريًا.</p>`;box.dataset.visible='true';box.scrollIntoView({behavior:'smooth',block:'nearest'})}
function cognitiveEngine(host,d){const saved=load(d),state=saved||{stage:0,trials:[],trial:0},stages=d.stages||5,per=d.trials_per_stage||6;let started=0,current=null;
function renderStage(){host.innerHTML=`<div class="lab-engine"><div class="stage-bar"><span style="width:${((state.stage+1)/stages)*100}%"></span></div><div class="stage-meta"><strong>المرحلة ${state.stage+1} من ${stages}</strong><span>${state.trials.length} محاولة محفوظة</span></div><div class="timer-card"><div class="stimulus">جاهز؟</div><div class="game-actions">${button('ابدأ المحاولة','start')}${button('إظهار النتيجة الحالية','secondary interim')}${button('حفظ وتوقف','secondary pause')}${button('بدء جديد','secondary restart')}</div></div><section class="result-card" aria-live="polite"></section></div>`;q('.start',host).onclick=nextTrial;q('.interim',host).onclick=()=>cognitiveResult(d,state,false);q('.pause',host).onclick=()=>{save(d,state);alert('تم حفظ المرحلة والنتائج على جهازك.')};q('.restart',host).onclick=()=>{if(confirm('بدء جديد ومسح النتائج؟')){clear(d);state.stage=0;state.trial=0;state.trials=[];renderStage()}}}
function nextTrial(){if(state.trial>=per){state.trial=0;if(state.stage>=stages-1){save(d,state);cognitiveResult(d,state,true);return}state.stage++;save(d,state);renderStage();return}current=makeTrial(d,state.stage,state.trial);started=now();const stim=q('.stimulus',host);stim.innerHTML=`<div><p>${current.prompt}</p><div class="game-actions">${current.options.map(o=>`<button type="button" data-value="${String(o).replace(/"/g,'&quot;')}">${o}</button>`).join('')}</div></div>`;qa('[data-value]',stim).forEach(b=>b.onclick=()=>{const value=b.dataset.value,correct=String(value)===String(current.answer);state.trials.push({correct,time:Math.round(now()-started),stage:state.stage});state.trial++;save(d,state);stim.innerHTML=`<div>${correct?'✓ صحيح':'✦ تابع التدريب'}</div>`;setTimeout(nextTrial,450)})}
renderStage()}
function legacyFix(){if(q('[data-v12-lab]'))return;const path=location.pathname;if(!/assessments|cognitive-tests/.test(path))return;qa('[id*="result" i],[class*="result" i],[hidden]').forEach(el=>{el.hidden=false;el.classList.add('legacy-result-fix')});const panel=document.createElement('aside');panel.className='lab-shell';panel.innerHTML=`<h2>مركز النتائج</h2><p>تم تفعيل إظهار مناطق النتائج المخفية في هذه الصفحة. للتجربة متعددة المراحل استخدم المختبر الجديد.</p><div class="game-actions"><button class="secondary">إظهار كل النتائج</button><a class="button" href="${/cognitive/.test(path)?BASE+'cognitive-lab/':BASE+'assessment-lab/'}">فتح المختبر الجديد</a></div>`;(q('main')||document.body).append(panel);q('button',panel).onclick=()=>qa('[id*="result" i],[class*="result" i],[hidden]').forEach(el=>{el.hidden=false;el.style.display='block';el.classList.add('legacy-result-fix')})}
function boot(){pastelize();const d=readDef(),a=q('[data-v12-lab="assessment"]'),c=q('[data-v12-lab="cognitive"]');if(d&&a)assessmentEngine(a,d);if(d&&c)cognitiveEngine(c,d);legacyFix();if('serviceWorker'in navigator)navigator.serviceWorker.register(BASE+'sw.js').catch(()=>{});let scheduled=false;const runAdded=nodes=>{if(scheduled)return;scheduled=true;const task=()=>{scheduled=false;nodes.forEach(node=>{if(node instanceof Element)pastelize(node)})};if('requestIdleCallback'in window)requestIdleCallback(task,{timeout:500});else setTimeout(task,50)};new MutationObserver(records=>{const nodes=[];records.forEach(record=>record.addedNodes.forEach(node=>nodes.push(node)));if(nodes.length)runAdded(nodes)}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();