"use strict";
const D=window.PA_DEMO_DATA,V="3",PASS="Explore-2026!";
const $=id=>document.getElementById(id),E=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const el={badge:$("mode-badge"),account:$("account-button"),ad:$("account-dialog"),af:$("account-form"),user:$("login-username"),pass:$("login-password"),visitor:$("visitor-mode-button"),contrast:$("contrast-toggle"),uid:$("current-uid"),role:$("current-role"),cc:$("case-count"),sc:$("session-count"),recent:$("recent-activity"),cases:$("cases-list"),cs:$("case-search"),cf:$("case-status-filter"),explorers:$("explorer-list"),es:$("explorer-search"),ef:$("explorer-category-filter"),professional:$("professional-list"),ps:$("professional-search"),pf:$("professional-category-filter"),cd:$("case-dialog"),cform:$("case-form"),cdd:$("case-detail-dialog"),cdc:$("case-detail-content"),assd:$("assessment-dialog"),assf:$("assessment-form"),assc:$("assessment-content"),rd:$("result-dialog"),rc:$("result-content"),live:$("live-region")};
let identity,store,selectedCase=null,selectedAssessment=null;
const k={ids:`pa-demo-identities-v${V}`,active:`pa-demo-active-v${V}`,contrast:`pa-demo-contrast-v${V}`},storeKey=u=>`pa-demo-store-v${V}:${u}`;
function get(key,f=null){try{let x=localStorage.getItem(key);return x===null?f:JSON.parse(x)}catch{return f}}
function set(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true}catch{toast("تعذر الحفظ المحلي.");return false}}
function id(p){let x=crypto?.randomUUID?.().replaceAll("-","").slice(0,16)??`${Date.now().toString(36)}${Math.random().toString(36).slice(2,9)}`;return`${p}-${x.toUpperCase()}`}
function toast(m){let n=document.createElement("div");n.className="toast";n.textContent=m;n.role="status";el.live.replaceChildren(n);setTimeout(()=>n.remove(),4500)}
function open(d){d.showModal?d.showModal():d.setAttribute("open","")}
function close(d){d.close?d.close():d.removeAttribute("open")}
function fmt(x){try{return new Intl.DateTimeFormat("ar-JO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x))}catch{return x}}
function labels(v){return({early:"الطفولة المبكرة",child:"الطفولة",adolescent:"المراهقة",adult:"البالغون",active:"نشطة",follow_up:"متابعة",closed:"مغلقة",self:"الشخص نفسه",parent:"والد أو مقدم رعاية",teacher:"المعلم أو المدرسة",provider:"مقدم خدمة",multiple:"مصادر متعددة"})[v]||v}
function identities(){let x=get(k.ids,{});return x&&typeof x==="object"?x:{}}
function visitor(){let x=identities();if(!x.__visitor__){x.__visitor__={uid:id("UID-VIS"),username:"visitor",role:"visitor",createdAt:new Date().toISOString()};set(k.ids,x)}return x.__visitor__}
function use(i){identity=i;set(k.active,{username:i.username,role:i.role});loadStore();render()}
function restore(){let a=get(k.active),x=identities();return a?.role==="provider"&&x[a.username]?x[a.username]:visitor()}
function loadStore(){store=get(storeKey(identity.uid));if(!store||store.uid!==identity.uid||!Array.isArray(store.cases)){store={uid:identity.uid,schemaVersion:V,cases:[],createdAt:new Date().toISOString()};save()}}
function save(){store.updatedAt=new Date().toISOString();set(storeKey(identity.uid),store)}
const fcase=x=>store.cases.find(c=>c.caseId===x),fass=x=>D.explorers.find(a=>a.id===x),cat=x=>D.categories.find(c=>c.id===x)?.label||x;
function countSessions(){return store.cases.reduce((n,c)=>n+c.sessions.length,0)}
function render(){const p=identity.role==="provider";el.badge.textContent=p?`مقدم خدمة تجريبي: ${identity.username}`:"وضع الزائر";el.badge.className=`badge ${p?"success":"neutral"}`;el.account.textContent=p?"تبديل الحساب":"الدخول التجريبي";el.uid.textContent=identity.uid;el.role.textContent=p?"مقدم خدمة تجريبي":"زائر استكشافي";el.cc.textContent=store.cases.length;el.sc.textContent=countSessions();renderCases();renderExplorers();renderProfessional();renderRecent()}
function renderRecent(){let a=[];store.cases.forEach(c=>{a.push({t:c.createdAt,n:`إنشاء ${c.alias}`,m:c.caseId});c.sessions.forEach(s=>a.push({t:s.completedAt,n:fass(s.assessmentId)?.title||s.assessmentId,m:`${c.alias} — ${s.outcomeLabel}`}))});a.sort((x,y)=>new Date(y.t)-new Date(x.t));el.recent.className=a.length?"activity-list":"empty-state";el.recent.innerHTML=a.length?a.slice(0,7).map(x=>`<div class="activity-item"><span class="activity-icon">ج</span><div><strong>${E(x.n)}</strong><p>${E(x.m)}</p></div><time>${E(fmt(x.t))}</time></div>`).join(""):"لا يوجد نشاط محفوظ بعد."}
function renderCases(){let q=el.cs.value.trim().toLowerCase(),st=el.cf.value,a=store.cases.filter(c=>(!st||c.status===st)&&(!q||`${c.alias} ${c.caseId} ${c.question}`.toLowerCase().includes(q))).sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt));el.cases.innerHTML=a.length?a.map(c=>`<article class="case-card"><div class="card-topline"><span class="badge ${c.status==="closed"?"neutral":"success"}">${labels(c.status)}</span><span class="code small">${E(c.caseId)}</span></div><h3>${E(c.alias)}</h3><p>${E(c.question)}</p><dl class="mini-grid"><div><dt>الفئة</dt><dd>${labels(c.ageGroup)}</dd></div><div><dt>الجلسات</dt><dd>${c.sessions.length}</dd></div><div><dt>التحديث</dt><dd>${E(fmt(c.updatedAt))}</dd></div></dl><div class="card-actions"><button class="button primary small-button" data-open-case="${E(c.caseId)}">فتح السجل</button><button class="button secondary small-button" data-assess-case="${E(c.caseId)}">بدء جلسة</button></div></article>`).join(""):`<div class="empty-state wide">لا توجد حالات مطابقة.</div>`}
function fillFilters(){if(el.ef.options.length===1)D.categories.forEach(c=>el.ef.add(new Option(c.label,c.id)));if(el.pf.options.length===1)[...new Set(D.professional.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,"ar")).forEach(c=>el.pf.add(new Option(c,c)))}
function renderExplorers(){let q=el.es.value.trim().toLowerCase(),c=el.ef.value,a=D.explorers.filter(x=>(!c||x.category===c)&&(!q||`${x.title} ${x.description} ${cat(x.category)}`.toLowerCase().includes(q)));el.explorers.innerHTML=a.map(x=>`<article class="assessment-card"><div class="card-topline"><span class="badge neutral">${E(cat(x.category))}</span><span>${E(x.duration)}</span></div><h3>${E(x.title)}</h3><p>${E(x.description)}</p><div class="meta-row"><span>${x.questions.length} عناصر</span><span>اختيارات + قائمة + ملاحظات</span></div><div class="card-actions"><button class="button primary small-button" data-start="${E(x.id)}">بدء الأداة</button><button class="button ghost small-button" data-guide="${E(x.id)}">طريقة العمل</button></div></article>`).join("")}
function renderProfessional(){let q=el.ps.value.trim().toLowerCase(),c=el.pf.value,a=D.professional.filter(x=>(!c||x.category===c)&&(!q||`${x.name} ${x.kind} ${x.note} ${x.category}`.toLowerCase().includes(q)));el.professional.innerHTML=a.length?a.map(x=>{let s={locked:["مقفل","danger"],guide:["دليل فقط","warning"],external:["خدمة خارجية","neutral"]}[x.status];return`<article class="catalog-row"><div><span class="catalog-category">${E(x.category)}</span><h3>${E(x.name)}</h3><p>${E(x.kind)}</p></div><div><strong>الوصول</strong><p>${E(x.access)}</p></div><div><span class="badge ${s[1]}">${s[0]}</span><p>${E(x.note)}</p></div></article>`}).join(""):`<div class="empty-state">لا توجد نتائج.</div>`}
function view(n){document.querySelectorAll(".tab").forEach(x=>{let a=x.dataset.view===n;x.classList.toggle("active",a);x.setAttribute("aria-selected",a)});document.querySelectorAll("[data-view-panel]").forEach(x=>{let a=x.dataset.viewPanel===n;x.hidden=!a;x.classList.toggle("active",a)});$(`view-${n}`)?.scrollIntoView({behavior:"smooth"})}
function newCase(){el.cform.reset();open(el.cd);setTimeout(()=>el.cform.elements.alias.focus(),0)}
function makeCase(fd){let now=new Date().toISOString(),c={caseId:id("CASE"),alias:fd.get("alias").trim(),ageGroup:fd.get("ageGroup"),language:fd.get("language"),informant:fd.get("informant"),question:fd.get("question").trim(),notes:fd.get("notes").trim(),status:"active",sessions:[],createdAt:now,updatedAt:now};store.cases.unshift(c);save();render();return c}
function sessionHtml(s){return`<article class="session-row"><div><span class="badge ${s.outcome==="urgent_stop"?"danger":s.outcome==="continue"?"warning":"success"}">${E(s.outcomeLabel)}</span><h4>${E(fass(s.assessmentId)?.title||s.assessmentId)}</h4><p>${E(s.summary)}</p>${s.note?`<p><strong>الملاحظة:</strong> ${E(s.note)}</p>`:""}</div><div class="session-meta"><time>${E(fmt(s.completedAt))}</time><span class="code small">${E(s.sessionId)}</span><button class="button ghost small-button" data-result="${E(s.sessionId)}">عرض النتيجة</button></div></article>`}
function showCase(cid){let c=fcase(cid);if(!c)return;selectedCase=cid;el.cdc.innerHTML=`<div class="dialog-heading"><div><p class="eyebrow">${E(c.caseId)}</p><h2>${E(c.alias)}</h2></div><button class="icon-button" data-close="case-detail-dialog">×</button></div><dl class="summary-grid"><div><dt>العمر</dt><dd>${labels(c.ageGroup)}</dd></div><div><dt>المصدر</dt><dd>${labels(c.informant)}</dd></div><div><dt>الحالة</dt><dd>${labels(c.status)}</dd></div></dl><div class="callout info"><strong>السؤال:</strong> ${E(c.question)}</div>${c.notes?`<p><strong>ملاحظات أولية:</strong> ${E(c.notes)}</p>`:""}<div class="section-heading compact"><div><h3>سجل الجلسات</h3><p class="muted">${c.sessions.length} جلسة</p></div><button class="button primary small-button" data-new-session="${E(cid)}">جلسة جديدة</button></div><div class="session-list">${c.sessions.length?[...c.sessions].reverse().map(sessionHtml).join(""):`<div class="empty-state">لم تسجل جلسات بعد.</div>`}</div><div class="dialog-actions spread"><div><button class="button ghost" data-export="${E(cid)}">تصدير JSON</button><button class="button ghost danger-text" data-delete="${E(cid)}">حذف محلي</button></div><label class="field inline-field"><span>حالة السجل</span><select data-status="${E(cid)}"><option value="active"${c.status==="active"?" selected":""}>نشطة</option><option value="follow_up"${c.status==="follow_up"?" selected":""}>متابعة</option><option value="closed"${c.status==="closed"?" selected":""}>مغلقة</option></select></label></div>`;open(el.cdd)}
function choose(aid){let a=store.cases.filter(c=>c.status!=="closed");if(!a.length){selectedAssessment=aid;toast("أنشئ حالة أولًا.");newCase();return}if(selectedCase&&a.some(c=>c.caseId===selectedCase)){start(selectedCase,aid);return}el.rc.innerHTML=`<div class="dialog-heading"><div><p class="eyebrow">ربط الجلسة</p><h2>اختر الحالة</h2></div><button class="icon-button" data-close="result-dialog">×</button></div><div class="choice-list">${a.map(c=>`<button class="case-choice" data-pick="${E(c.caseId)}" data-aid="${E(aid)}"><strong>${E(c.alias)}</strong><span>${E(c.caseId)} — ${labels(c.ageGroup)}</span></button>`).join("")}</div><button class="button secondary" data-create-for="${E(aid)}">إنشاء حالة جديدة</button>`;open(el.rd)}
function guide(aid){let a=fass(aid);if(!a)return;el.rc.innerHTML=`<div class="dialog-heading"><div><p class="eyebrow">${E(cat(a.category))}</p><h2>${E(a.title)}</h2></div><button class="icon-button" data-close="result-dialog">×</button></div><p class="lead-small">${E(a.description)}</p><div class="guide-box"><h3>طريقة التطبيق</h3><ol>${a.guide.map(x=>`<li>${E(x)}</li>`).join("")}</ol></div><div class="callout warning">النتيجة تنظم مجالات الاستكشاف فقط ولا تنتج تشخيصًا أو درجة معيارية.</div><div class="dialog-actions"><button class="button primary" data-start="${E(a.id)}">بدء الأداة</button></div>`;open(el.rd)}
function question(q,i){let r="",req=q.required===false?"":"required";if(q.type==="radio")r=`<div class="option-grid">${q.options.map(o=>`<label class="option-card"><input type="radio" name="${E(q.id)}" value="${E(o[0])}" ${req}><span>${E(o[1])}</span></label>`).join("")}</div>`;else if(q.type==="checkbox")r=`<div class="option-grid">${q.options.map(o=>`<label class="option-card"><input type="checkbox" name="${E(q.id)}" value="${E(o[0])}"><span>${E(o[1])}</span></label>`).join("")}</div>`;else if(q.type==="select")r=`<select name="${E(q.id)}" ${req}><option value="">اختر الإجابة</option>${q.options.map(o=>`<option value="${E(o[0])}">${E(o[1])}</option>`).join("")}</select>`;else r=`<textarea name="${E(q.id)}" rows="3" maxlength="${q.maxLength||800}" ${req} placeholder="اكتب ملاحظة وصفية"></textarea>`;return`<fieldset class="question-card"><legend><span>${i+1}</span>${E(q.text)}</legend>${r}</fieldset>`}
function start(cid,aid){let c=fcase(cid),a=fass(aid);if(!c||!a)return;if(!a.ages.includes(c.ageGroup)){toast("الأداة غير مهيأة لهذه الفئة العمرية.");return}selectedCase=cid;selectedAssessment=aid;el.assc.innerHTML=`<div class="dialog-heading"><div><p class="eyebrow">${E(c.alias)} — ${E(c.caseId)}</p><h2>${E(a.title)}</h2></div><button class="icon-button" data-close="assessment-dialog">×</button></div><div class="assessment-intro"><p>${E(a.description)}</p><span class="badge neutral">${E(a.duration)}</span></div><div class="callout warning">أجب وفق الأداء المعتاد واختر غير معروف بدل التخمين.</div><div class="question-list">${a.questions.map(question).join("")}</div><div class="review-fields"><label class="field"><span>${identity.role==="provider"?"الملاحظة المهنية":"ملاحظتك"}</span><textarea name="sessionNote" rows="4" maxlength="1600"></textarea></label>${identity.role==="provider"?`<label class="field"><span>قرار مقدم الخدمة المبدئي</span><select name="providerDecision"><option value="">يحدد بعد المراجعة</option><option value="finish">إنهاء ومتابعة روتينية</option><option value="next_tool">استكمال أداة أخرى</option><option value="collect_data">جمع معلومات إضافية</option><option value="professional_referral">اقتراح تقييم مهني</option></select></label>`:""}</div><div class="dialog-actions"><button class="button ghost" data-close="assessment-dialog">إلغاء</button><button class="button primary" type="submit">إنهاء الجلسة وحفظها</button></div>`;open(el.assd)}
function weight(q,v){if(q.type==="textarea")return null;if(q.type==="checkbox")return v.reduce((n,x)=>n+(q.options.find(o=>o[0]===x)?.[2]||0),0);let o=q.options.find(o=>o[0]===v);return typeof o?.[2]==="number"?o[2]:null}
function complete(ev){ev.preventDefault();if(!el.assf.reportValidity())return;let c=fcase(selectedCase),a=fass(selectedAssessment);if(!c||!a)return;let fd=new FormData(el.assf),ans={},dom={},total=0,n=0,urgent=false,concern=false;for(let q of a.questions){let v=q.type==="checkbox"?fd.getAll(q.id):fd.get(q.id)||"";if(q.type==="checkbox"&&!v.length){toast("اختر إجابة واحدة على الأقل في السؤال متعدد الاختيارات.");return}ans[q.id]=v;if(q.safety){urgent=v==="immediate";concern=v==="concern"}let w=weight(q,v);if(w!==null){dom[q.domain]=(dom[q.domain]||0)+w;total+=w;n++}}let avg=n?total/n:0,outcome="finish",label="إنهاء الجلسة بمتابعة روتينية",summary="لم تظهر أولوية مرتفعة ثابتة في هذه الإجابات، مع أهمية متابعة السياق.";if(urgent){outcome="urgent_stop";label="إيقاف الأداة واتباع مسار السلامة";summary="تم الإبلاغ عن خطر مباشر أو وشيك. يجب اتباع خدمات الطوارئ أو بروتوكول السلامة المحلي فورًا."}else if(concern||avg>=1.5){outcome="continue";label="جمع معلومات أو تقييم متخصص";summary="توجد مجالات متعددة تستحق مراجعة مختص وجمع معلومات إضافية."}else if(avg>=.7){outcome="continue";label="استكمال أداة استكشافية تالية";summary="توجد مؤشرات متوسطة أو متباينة تستحق استكشافًا منظمًا."}let next=urgent?null:a.next.map(fass).find(x=>x&&x.ages.includes(c.ageGroup));if(outcome==="finish")next=null;let now=new Date().toISOString(),s={sessionId:id("SES"),assessmentId:a.id,completedAt:now,answers:ans,domainSignals:dom,averageSignal:+avg.toFixed(2),outcome,outcomeLabel:label,summary,recommendation:{assessmentId:next?.id||null,label:next?`الأداة المقترحة: ${next.title}`:urgent?"لا توجد أداة تالية قبل إغلاق مسار السلامة.":"إنهاء الجلسة مع متابعة التغيرات."},note:String(fd.get("sessionNote")||"").trim(),providerDecision:String(fd.get("providerDecision")||""),completedByUid:identity.uid,completedByRole:identity.role};c.sessions.push(s);c.updatedAt=now;if(urgent)c.status="follow_up";save();render();close(el.assd);result(c,s)}
function dlabel(x){return({communication:"التواصل",learning:"التعلم",participation:"المشاركة",receptive:"فهم اللغة",expressive:"التعبير",functional:"التواصل الوظيفي",initiation:"بدء المهمة",sustained:"استمرار الانتباه",organization:"التنظيم",instruction:"فرص التعليم",reading:"القراءة",supports:"التكييفات",self_care:"العناية الذاتية",safety:"السلامة اليومية",community:"المشاركة المجتمعية",sound:"الأصوات",touch:"اللمس",visual:"البيئة البصرية",mobility:"التنقل",balance:"التوازن",access:"الوصول",intensity:"شدة الانفعال",recovery:"التعافي",risk:"السلامة الحالية"})[x]||x}
function result(c,s){let a=fass(s.assessmentId),cl=s.outcome==="urgent_stop"?"danger":s.outcome==="continue"?"warning":"success";el.rc.innerHTML=`<div class="dialog-heading"><div><p class="eyebrow">${E(c.alias)} — ${E(s.sessionId)}</p><h2>نتيجة ${E(a?.title||s.assessmentId)}</h2></div><button class="icon-button" data-close="result-dialog">×</button></div><div class="result-hero ${cl}"><span class="badge ${cl}">${E(s.outcomeLabel)}</span><p>${E(s.summary)}</p></div>${s.outcome==="urgent_stop"?`<div class="callout danger"><strong>توقف الآن:</strong> تواصل مع خدمات الطوارئ المحلية أو جهة صحية عاجلة، ولا تعتمد على المنصة لإدارة الطوارئ.</div>`:""}<div class="section-heading compact"><div><h3>المجالات الظاهرة</h3><p class="muted">وصف داخل الجلسة وليس درجة معيارية.</p></div></div><div class="signal-grid">${Object.entries(s.domainSignals).map(([d,v])=>`<div class="signal-card"><span>${E(dlabel(d))}</span><strong>${v===0?"لا إشارة":v===1?"إشارة محدودة":"يستحق الاستكشاف"}</strong></div>`).join("")||`<div class="empty-state">لا توجد عناصر قابلة للتلخيص.</div>`}</div><div class="recommendation-box"><h3>الخطوة التالية</h3><p>${E(s.recommendation.label)}</p>${s.note?`<p><strong>ملاحظة الجلسة:</strong> ${E(s.note)}</p>`:""}</div><div class="callout info">يمكن لمقدم الخدمة إكمال صياغته المهنية، لكن المنصة لا تنتج تشخيصًا تلقائيًا.</div><div class="dialog-actions"><button class="button ghost" data-back-case="${E(c.caseId)}">فتح سجل الحالة</button>${s.recommendation.assessmentId?`<button class="button primary" data-next="${E(s.recommendation.assessmentId)}" data-cid="${E(c.caseId)}">بدء الأداة التالية</button>`:""}</div>`;open(el.rd)}
function findSession(sid){for(let c of store.cases){let s=c.sessions.find(x=>x.sessionId===sid);if(s)return[c,s]}}
function exportCase(cid){let c=fcase(cid);if(!c)return;let b=new Blob([JSON.stringify({warning:"Exploratory non-diagnostic local demo data",ownerUid:identity.uid,case:c},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`${c.caseId}.json`;a.click();URL.revokeObjectURL(u)}
document.addEventListener("click",e=>{let t=e.target.closest("button,a");if(!t)return;if(t.matches(".tab"))view(t.dataset.view);if(t.id==="account-button")open(el.ad);if(t.id==="start-explore")view("explorers");if(t.id==="open-guide")view("guide");if(["dashboard-new-case","new-case-button"].includes(t.id))newCase();if(t.id==="copy-uid"){navigator.clipboard?.writeText(identity.uid);toast("تم نسخ UID.")}if(t.dataset.openCase)showCase(t.dataset.openCase);if(t.dataset.assessCase){selectedCase=t.dataset.assessCase;close(el.cdd);view("explorers");toast("اختر الأداة المناسبة.")}if(t.dataset.start){close(el.rd);choose(t.dataset.start)}if(t.dataset.guide)guide(t.dataset.guide);if(t.dataset.pick){close(el.rd);start(t.dataset.pick,t.dataset.aid)}if(t.dataset.createFor){selectedAssessment=t.dataset.createFor;close(el.rd);newCase()}if(t.dataset.newSession){selectedCase=t.dataset.newSession;close(el.cdd);view("explorers")}if(t.dataset.result){let x=findSession(t.dataset.result);if(x)result(...x)}if(t.dataset.backCase){close(el.rd);showCase(t.dataset.backCase)}if(t.dataset.next){close(el.rd);start(t.dataset.cid,t.dataset.next)}if(t.dataset.export)exportCase(t.dataset.export);if(t.dataset.delete){let c=fcase(t.dataset.delete);if(c&&confirm(`حذف ${c.alias} وجميع جلساته؟`)){store.cases=store.cases.filter(x=>x.caseId!==c.caseId);save();render();close(el.cdd)}}if(t.dataset.close)close($(t.dataset.close))});
el.af.addEventListener("submit",e=>{e.preventDefault();let u=el.user.value.trim().toLowerCase();if(!/^[a-z0-9._-]{3,40}$/.test(u)){toast("استخدم اسمًا إنجليزيًا من 3 إلى 40 رمزًا.");return}if(el.pass.value!==PASS){toast("رمز العرض غير صحيح.");return}let x=identities();if(!x[u])x[u]={uid:id("UID-PROV"),username:u,role:"provider",createdAt:new Date().toISOString()};set(k.ids,x);use(x[u]);close(el.ad);el.af.reset();toast("فُتحت مساحة مقدم الخدمة المنفصلة.")});
el.visitor.addEventListener("click",()=>{use(visitor());close(el.ad);toast("تم التبديل إلى وضع الزائر.")});
el.contrast.addEventListener("click",()=>{let x=!document.body.classList.contains("high-contrast");document.body.classList.toggle("high-contrast",x);el.contrast.ariaPressed=x;el.contrast.textContent=x?"التباين القياسي":"تباين مرتفع";set(k.contrast,x)});
el.cform.addEventListener("submit",e=>{e.preventDefault();if(!el.cform.reportValidity())return;let c=makeCase(new FormData(el.cform));close(el.cd);toast("تم إنشاء الحالة داخل UID الحالي.");if(selectedAssessment){let a=selectedAssessment;selectedAssessment=null;start(c.caseId,a)}else showCase(c.caseId)});
el.assf.addEventListener("submit",complete);
[el.cs,el.es,el.ps].forEach((x,i)=>x.addEventListener("input",[renderCases,renderExplorers,renderProfessional][i]));[el.cf,el.ef,el.pf].forEach((x,i)=>x.addEventListener("change",[renderCases,renderExplorers,renderProfessional][i]));
el.cdc.addEventListener("change",e=>{let s=e.target.closest("[data-status]");if(!s)return;let c=fcase(s.dataset.status);if(c){c.status=s.value;c.updatedAt=new Date().toISOString();save();render();showCase(c.caseId)}});
document.addEventListener("change",e=>{let x=e.target;if(!(x instanceof HTMLInputElement)||x.type!=="checkbox")return;let f=x.closest(".question-card"),n=f?.querySelector('input[value="none"]');if(!n)return;if(x===n&&x.checked)f.querySelectorAll('input[type="checkbox"]:not([value="none"])').forEach(y=>y.checked=false);else if(x.checked)n.checked=false});
document.body.classList.toggle("high-contrast",!!get(k.contrast,false));fillFilters();identity=restore();loadStore();render();
